### ISSUE TITLE
Add OAuth providers

### ISSUE THREAD

**Issue by cuire** [pockethost/pockethost#319]
I did the research. By default, Pocketbase allows you to login via oauth if the email is the same. But it does not allow registration with creditnails if email is used in oauth. 
If its sutable for the project (probably yes) I can start working on UI once we've defined the list of providers.
I think must have is google and github. 
Also I need to know is 'main' pb instance is updated to use ['one call OAuth'](https://pocketbase.io/docs/authentication/#oauth2-integration).
Also in UI we can call for [list-providers](https://pocketbase.io/docs/api-records/#list-auth-methods) and mark buttons disabled when providers not enabled server side.

**Comment by brewhousedigital** [comment]
Hey @cuire , I think you might be in the wrong repo. PocketHost is a hosting platform for PocketBase. If you want to ask any questions about OAuth, open a discussion item here: https://github.com/pocketbase/pocketbase

For your question about the "main" pb instance, for PocketHost, just make sure whatever instance you are running is up to date. That way you get all the latest PocketBase features.

For the List Providers system, the link you posted answers your question:
`const result = await pb.collection('users').listAuthMethods();`

**Comment by cuire** [comment]
This issue about adding oauth to poskethost. I apologize if I expressed myself incorrectly. https://github.com/pockethost/pockethost/discussions/316#discussioncomment-7217798

**Comment by brewhousedigital** [comment]
Oh I see, you're interested in adding OAuth login to PocketHost then? Github and Google?

**Comment by cuire** [comment]
These are must have, but I want to hear preferences for other providers. 
I want to do UI things and then someone from mainteners will setup OAuth apps in google cloud and github etc.

**Comment by brewhousedigital** [comment]
Lets move this over to our Discussion session. I updated the title of your original Discussion to "Adding in OAuth Support to PocketHost".

https://github.com/pockethost/pockethost/discussions/316
