### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by DDuran19** [pockethost/pockethost#332]
When clicking on  the [PocketBase Web APIs](https://pockethost.io/docs//api-records/) under Additional resources, it results to a broken link due to incorrect address on the anchor tag.

![image](https://github.com/pockethost/pockethost/assets/128191960/a0ba47c6-079c-42a7-8ed4-e6317bbf5014)
![image](https://github.com/pockethost/pockethost/assets/128191960/7280b198-b80b-4b0a-ac82-40055c22154e)

![image](https://github.com/pockethost/pockethost/assets/128191960/d2cbc359-bb35-4d71-8dde-1dd8547edd21)

**Comment by brewhousedigital** [comment]
@benallfree This is odd... the code doesn't have that extra slash but I see it in the dashboard. Any ideas?

https://github.com/pockethost/pockethost/blob/master/frontends/dashboard/src/routes/app/instances/%5BinstanceId%5D/Code.svelte#L43

**Comment by benallfree** [comment]
Should already be fixed in master
