### ISSUE TITLE
Docs on FTP access are outdated

### ISSUE THREAD

**Issue by ChrisPoul** [pockethost/pockethost#333]
I tryied connecting via FTP as instructed in the [docs](https://pockethost.io/docs/usage/ftp/#accessing-via-ftp), I was not able to connect and then I found on the discord server that the host is no longer pockethost.io but instead ftp.sfo-1.pockethost.io, this should be reflected on the docs, thanks.

**Comment by benallfree** [comment]
Thank you! Please send a PR if you have time :)

**Comment by ChrisPoul** [comment]
> Thank you! Please send a PR if you have time :)

Yes I would love to and I have the commit ready but it looks like I don't have access to push my branch, could you give me a hand with that?

**Comment by benallfree** [comment]
You have to first fork the project and then push to your own fork. From there you can initiate a PR :)
