### ISSUE TITLE
500 When trying to sing up

### ISSUE THREAD

**Issue by Jesspu** [pockethost/pockethost#339]
When attempting to sing up for pocket host, I am receiving a 500 error, with the message 

`Could not create instance: Invalid version ~0.19.0. Version must be one of: 0.19.*, 0.19.4, 0.19.3, 0.19.2, 0.19.1, 0.19.0, 0.18.*, 0.18.10, 0.18.9, 0.18.8, 0.18.7, 0.18.6, 0.18.5, 0.18.4, 0.18.3, 0.18.2, 0.18.1, 0.18.0, 0.17.*, 0.17.7, 0.17.6, 0.17.5, 0.17.4, 0.17.3, 0.17.2, 0.17.1, 0.17.0, 0.16.*, 0.16.10, 0.16.9, 0.16.8, 0.16.7, 0.16.6, 0.16.5, 0.16.4, 0.16.3, 0.16.2, 0.16.1, 0.16.0, 0.15.*, 0.15.3, 0.15.2, 0.15.1, 0.15.0, 0.14.*, 0.14.5, 0.14.4, 0.14.3, 0.14.2, 0.14.1, 0.14.0, 0.13.*, 0.13.4, 0.13.3, 0.13.2, 0.13.1, 0.13.0, 0.12.*, 0.12.3, 0.12.2, 0.12.1, 0.12.0, 0.11.*, 0.11.4, 0.11.3, 0.11.2, 0.11.1, 0.11.0, 0.10.*, 0.10.4, 0.10.3, 0.10.2, 0.10.1, 0.10.0, 0.9.*, 0.9.2, 0.9.1, 0.9.0, 0.8.*, 0.8.0, 0.7.*, 0.7.10, 0.7.9, 0.7.8, 0.7.7, 0.7.6, 0.7.5, 0.7.4, 0.7.3, 0.7.2, 0.7.1, 0.7.0, 0.6.*, 0.6.0, 0.5.*, 0.5.2, 0.5.1, 0.5.0, 0.4.*, 0.4.2, 0.4.1, 0.4.0, 0.3.*, 0.3.4, 0.3.3, 0.3.2, 0.3.1, 0.3.0, 0.2.*, 0.2.8, 0.2.7.`

Not sure what this version is, but seems to be hardcoded on [this line](https://github.com/pockethost/pockethost/blob/3c95e5ae146a28b73781fdcb79dfd97fcc4550b4/src/mothership-app/pb_hooks/src/signup.pb.js#L165)

Does `~0.19.0` need to be added to [verisons.pb.js](https://github.com/pockethost/pockethost/blob/3c95e5ae146a28b73781fdcb79dfd97fcc4550b4/src/mothership-app/pb_hooks/src/versions.pb.js)?

If so, I can open a PR with the change, just not familiar enough with the expected operation. 

Thanks

**Comment by benallfree** [comment]
Sorry about that, please give it a shot now 👍
