### ISSUE TITLE
Deleting an Instance

### ISSUE THREAD

**Issue by brewhousedigital** [pockethost/pockethost#35]
Is there currently a way to delete / remove an instance? 

If so, does that need to be added to the Instance Details page somewhere?

**Comment by benallfree** [comment]
I think I’ll wait until I have better stats tracking. Deleting an instance or reusing a subdomain might be problematic for reporting. But definitely archiving an instance.

**Comment by brewhousedigital** [comment]
What are your thoughts on adopting a naming structure like Netlify and Vercel use? where it's `word-word-randomInteger`

`https://random-app-384729.pockethost.io` ?

**Comment by benallfree** [comment]
I think that could be fine, especially after I add custom domains support from #25.

**Comment by brewhousedigital** [comment]
Do you have a maximum name length configured for the generated domain name?

**Comment by benallfree** [comment]
I’d have to look. 50 chars seems fine, but I don’t really have any reason for that :)

**Comment by benallfree** [comment]
Let's do #42 first, then we can work on archival here.

**Comment by benallfree** [comment]
moving to roadmap

**Comment by benallfree** [comment]
* add button in Danger Zone 
* Button is disabled unless in maintenance mode
* Confirm the instance should be deleted
* Create an rpc call to delete an instance (hygen)
* To delete: set instance record deletedAt to current time
* Deleted instance appears in UI as deleted with X days remaining to revert
* In Danger Zone, the delete button becomes undelete
* Make an rpc call to set deletedAt to null again
* Create a new backend service that runs once per minute and looks for instances that have stayed deleted for 30 days. Set purgedAt to current data and recursively remove instance files. 
* purgedAt instances do not show in UI or ftp
* deletedAt instances show ‘this instance has been deleted’ if their url is hit
* purgedAt instances respond as if not found
* subdomain of purgedAt instance can be reused 
* purgedAt instances cannot be undeleted

**Comment by IAmRiteshKoushik** [comment]
Are we opening sub-issues for these or shall we keep all the discussion in this one issue ?

**Comment by benallfree** [comment]
@IAmRiteshKoushik No sub issues those are just the steps that need to be covered to delete an instance. We need that code in place to do #172

**Comment by IAmRiteshKoushik** [comment]
I do not have any expertise in Svelte, I work in Vuejs so; making the UI changes is currently  beyond my scope

**Comment by benallfree** [comment]
@IAmRiteshKoushik It's up to you, this task requires both frontend and backend work though.

**Comment by IAmRiteshKoushik** [comment]
I will try to look for issues in the ROADMAP which are tend to fall under my expertise. The framework to solve this issue is out of my scope. Thank you for your patience @benallfree

**Comment by benallfree** [comment]
@IAmRiteshKoushik Thank you for checking it. We will leave this issue open in case someone else wants to try (or me).

**Comment by benallfree** [comment]
Closing for https://discord.com/channels/1128192380500193370/1158527634884530247
