### ISSUE TITLE
Dart SDK throwing a weird error

### ISSUE THREAD

**Issue by Jadi255** [pockethost/pockethost#354]
Here's the error log:

E/flutter (30596): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: ClientException: {url: https://ahrar.pockethost.io/api/realtime, isAbort: false, statusCode: 526, response: {}, originalError: null}
E/flutter (30596): #0      PocketBase.send (package:pocketbase/src/client.dart:236:9)
E/flutter (30596): <asynchronous suspension>
E/flutter (30596): #1      RealtimeService._connect.<anonymous closure> (package:pocketbase/src/services/realtime_service.dart:276:7)
E/flutter (30596): <asynchronous suspension>

Looking at the PocketHost repo, I noticed a commit about 1 hour ago, around the time I started having issues. Related? 

**EDIT**
after some more troubleshooting, I tried accessing the database dashboard directly in my browser and it's telling me there's an invalid SSL certificate

**Comment by brewhousedigital** [comment]
From the PocketHost maintainer: 
> There was a security update to PocketHost. CloudFlare now uses "Full" SSL encryption, meaning traffic is encrypted not just between browser and Cloudflare, but also between Cloudflare and the PocketHost origin. We are running the Caddy HTTP server (golang) on the server now, and it provides automatic SSL and proxies things to the PocketHost nodejs server if it passes all the Caddy security checks. You may get some temporary "526 certificate invalid" errors from Cloudflare until all the caches change over, but it should be resolved within a few hours. If it is not, please let me know.

**Comment by benallfree** [comment]
@Jadi255 Yes @brewhousedigital is correct, sorry about that. We are trying to do some security updates but something appears to be going wrong with Cloudflare. If you get this error intermittently over the next day, that is likely the cause. If it persists beyond that, please re-open this issue.

https://discord.com/channels/1128192380500193370/1179854182363173005/1189229738967961600
