### ISSUE TITLE
Bug: hard-refreshing instance view results in blank page

### ISSUE THREAD

**Issue by benallfree** [pockethost/pockethost#365]
@brewhousedigital a user reported this bug

If you go to an instance, like https://app.pockethost.io/app/instances/o2anhefj3k491b8

then hard refresh the browser, the page will be blank

if you have time can you look into this? otherwise i will

**Comment by brewhousedigital** [comment]
Sure thing!

**Comment by benallfree** [comment]
Closed by #366
