### ISSUE TITLE
Instance rename

### ISSUE THREAD

**Issue by bloor** [pockethost/pockethost#375]
![image](https://github.com/pockethost/pockethost/assets/1420653/976f91e0-6906-4cb2-a02a-0479291e21cf)

.. subdomains are allowed to use numbers as well.
Can you add numbers to the regex ? Currently my need for "d1map" instance name is not possible.

**Comment by benallfree** [comment]
@bloor  This looks like only a frontend issue. The backend regex is `^[a-z][a-z0-9-]{2,39}$`. If you want to submit a PR correcting the frontend regex, please do!

@WombleWoo7547 Can you please share more info about the compatibility issues with PocketBase? I'm not understanding.
