### ISSUE TITLE
CLI womp womp

### ISSUE THREAD

**Issue by WombleWoo7547** [pockethost/pockethost#378]
CLI is broken
I run
```bash
npx pockethost serve
```
and get a response of
```
npm ERR! could not determine executable to run

npm ERR! A complete log of this run can be found in: /Users/USER REMOVED/.npm/_logs/2024-04-06T09_42_48_668Z-debug-0.log
```

**___Hardware/software___**
- Mid 2015 Macbook Pro - MacOS Monterey 12.7.4 - NodeJS 21.5.0 `(log mentioned)`
- Raspberry Pi 4 (for compatibility checking) - Ubuntu 22.04 LTS - NodeJS 21.5.0
- Virtualbox VM - Windows 10 - 22H2 - NodeJS 21.5.0
   - WSL
   - Powershell
   - Git bash

**Comment by benallfree** [comment]
Closing til next release.
