### ISSUE TITLE
Pockethost Down

### ISSUE THREAD

**Issue by cheskoxd** [pockethost/pockethost#391]
I'm getting Gateway time-out - Error Code 504 when accessing any instance
![image](https://github.com/user-attachments/assets/7616ab0b-81e5-4dbb-b52b-fde18f87c119)

**Comment by cheskoxd** [comment]
Now the login at app.pockethost.io is down too
![image](https://github.com/user-attachments/assets/13bb3c68-9f61-4f56-9e5c-c736e749a76a)

It seems to be a cors issue
![image](https://github.com/user-attachments/assets/88d72887-3f6c-4518-8140-f76ea5094bc6)

**Comment by benallfree** [comment]
We're back up. For fastest support, please use [our Discord server](https://discord.gg/nVTxCMEcGT).
