### ISSUE TITLE
Improve synergy with Github action deployment

### ISSUE THREAD

**Issue by davidbarton** [pockethost/pockethost#394]
I have added a PocketHost deployment via a [`SamKirkland/FTP-Deploy-Action`](https://github.com/marketplace/actions/ftp-deploy) Github action. Here is my workflow config https://github.com/davidbarton/pocketbase-cookie-auth-demo/blob/main/.github/workflows/main.yml.

This Github action uses a state file (`.ftp-deploy-sync-state.json`) to make future syncs easier. Yet I have trouble finding a place for this file. I am unable to place it in the app root and the best dir I could come up with is the `pb_hooks`. Is there a better to place to keep such state files? Can we allow for such location on the ftp server please?

Ps: I must confess I am not a fan of software deployment over ftp but I get the reasons why it is done this way.

**Comment by benallfree** [comment]
Hey that's cool though!

Yes, we'd love to get an SSH server up and running. It's on the list, but so far it hasn't been solvable because we'd need some kind of SSH server that presents a virtual filesystem to the user based on their login info. 

Can you explain a little more about `.ftp-deploy-sync-state.json` and what it does? Does it store the commit hash or something? Probably `pb_hooks` or `pb_data` would be fine.

**Comment by davidbarton** [comment]
The SSH server you are looking for is used by the https://rsync.net backup. Perhaps this information can help you look for OSS alternatives.

I did just peeked into the Github action source code. It seems they only store file path and hash for each file. On next upload they compare those file hashes.

The `pb_hooks` location does the job. Yet it is meant to store different resource and abusing it for this state file is not correct. That's why I looked for different location. Simply whitelisting `.ftp-deploy-sync-state.json` in project root would be the easiest option since it would work out of box.

**Comment by benallfree** [comment]
https://discord.com/channels/1128192380500193370/1274218809971970118

**Comment by davidbarton** [comment]
I am sorry I do not use discord and it does not allow any preview or such.

**Comment by benallfree** [comment]
FYI the CLI version works:

```
bunx ftp-deploy --server ftp.sfo-1.pockethost.io --username ### --password ### --local-dir app/ --server-dir makerlist/pb_public/ --log-level verbose
```

**Comment by benallfree** [comment]
https://github.com/davidbarton/pocketbase-cookie-auth-demo/blob/2ad8e28e8cdf463f8386ce4d41532d7cde344b89/.github/workflows/main.yml#L24 should be `<instance-name>/pb_public`

**Comment by benallfree** [comment]
This will cover hooks, migrations, and static files assuming:

```
app/
   pb_public
   pb_hooks
   pb_migrations
```

```ts
import { deploy, excludeDefaults } from "@samkirkland/ftp-deploy";
import "dotenv/config";

async function deployMyCode() {
  console.log("🚚 Deploy started");
  await deploy({
    server: "ftp.sfo-1.pockethost.io",
    username: process.env.PH_USERNAME,
    password: process.env.PH_PASSWORD,
    "local-dir": "app/",
    "server-dir": "makerlist/",
    "state-name": "pb_public/.ftp-deploy-sync-state.json",
    // "log-level": "verbose",
  });
  console.log("🚀 Deploy done!");
}

deployMyCode();
```

**Comment by davidbarton** [comment]
Thanks for answer, so the only change for me is to do `<instance-name>/pb_public`. I think it is not a good idea since it is going to make the state file available on internet for no reason 🤷‍♀️. And it should live in the `<instance-name>/` root instead.

Anyway I got my answer and will close the issue.

**Comment by benallfree** [comment]
You can now write to the root.

**Comment by davidbarton** [comment]
Updated, thanks! https://github.com/davidbarton/pocketbase-cookie-auth-demo/commit/bbbade9a0f0ea5db7c14e98ae87aafaaa0465061
