### ISSUE TITLE
net::ERR_QUIC_PROTOCOL_ERROR 200 (OK)

### ISSUE THREAD

**Issue by Mashiane** [pockethost/pockethost#400]
Hi there

I have just implemented realtime api on my app and I am getting the error as indicated in the title of this message.

Can you please advise.

Thanks in advance.

**Comment by benallfree** [comment]
Hello, please use https://pockethost.io/support.

**Comment by boustanihani** [comment]
@Mashiane I am getting this error too, did you figure out what is causing this?

**Comment by benallfree** [comment]
@boustanihani Is it causing a problem? Some users see this, but it doesn't seem to be affecting anything.

**Comment by boustanihani** [comment]
It doesn't seem to be affecting anything until now, just wanted to report this.
